spring:
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ljj5kfijqs1fp4vg:djl78120tj7vx348@n2o93bb1bwmn0zle.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/q9dwfkike78ql3iy?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=Europe/Moscow
    username: ljj5kfijqs1fp4vg
    password: djl78120tj7vx348
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        storage_engine: innodb
        jdbc:
          timezone: UTC
  output:
    ansi:
      enabled: ALWAYS
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mail:
    host: smtp.yandex.ru
    username: jm-online-store@yandex.ru
    password: jm2020
    port: 465
    protocol: smtps
    debug: true
  server:
    url: http://localhost:9999
  mvc:
    static-path-pattern: /static/**
server:
  port: 9999
logging:
  file:
    name: src/main/logs/my.log
    max-history: 1
  level:
    com:
      jm: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %highlight(%-5level) %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
emailStockSending:
  delay: '0 0 10 */1 * *'

price-list-service:
  path-to-xls-file: uploads/files/prices/pricedaily.xls
  path-to-zip-file: uploads/files/prices/pricedaily.zip

delete_expired_customer_period:
  cron: '0 0 0 * * *'

spring.profiles.include: 'security'


# Смотри инструкцию https://trello.com/c/8akD9MhL
telegram-bot:
  name: JM_store_bot
  token: 1432791063:AAH1j664T9RnRPhS7elFAfvFcA5enPunWeE
  webhook-path: https://ad7f6a7f7482.ngrok.io/telegram-bot